-- AlterTable
ALTER TABLE `Cuota` MODIFY `fechaInicio` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `LineaDeCuota` MODIFY `fechaPago` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `UsuarioRol` MODIFY `fechaInicio` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
